// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT9mDtAxyLWfZ9kPglAu4jK83DzHZGqu4',
    appId: '1:699153284872:web:f212969384a3d1c506f6bd',
    messagingSenderId: '699153284872',
    projectId: 'fir-e10d0',
    authDomain: 'fir-e10d0.firebaseapp.com',
    storageBucket: 'fir-e10d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUuKqurDEBf_s1Yf8p5p3Oxhv9Xq7PzLk',
    appId: '1:699153284872:android:49dddd7ecbda989b06f6bd',
    messagingSenderId: '699153284872',
    projectId: 'fir-e10d0',
    storageBucket: 'fir-e10d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwPLX3pSJIdzxOt_T-QD19BHuVT4wswo',
    appId: '1:699153284872:ios:74007255b57d352006f6bd',
    messagingSenderId: '699153284872',
    projectId: 'fir-e10d0',
    storageBucket: 'fir-e10d0.appspot.com',
    iosClientId: '699153284872-p4mk8f640b13ulouau5og5k6h45qorf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALwPLX3pSJIdzxOt_T-QD19BHuVT4wswo',
    appId: '1:699153284872:ios:74007255b57d352006f6bd',
    messagingSenderId: '699153284872',
    projectId: 'fir-e10d0',
    storageBucket: 'fir-e10d0.appspot.com',
    iosClientId: '699153284872-p4mk8f640b13ulouau5og5k6h45qorf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
